---
output: html_document
editor_options: 
  chunk_output_type: console
---

## Univariate Distributions

A normal distribution, also known as a Gaussian distribution, is a continuous probability distribution that has a bell-shaped curve. The normal distribution is characterized by two parameters: the mean ($\mu$) and the standard deviation ($\sigma$). The following are the key properties of a normal density curve:

-   Symmetry: The curve is symmetric around the mean.
-   Unimodal: The curve has a single peak, known as the mode, which coincides with the mean and the median.
-   Asymptotic: The tails of the curve extend infinitely in both directions, approaching but never touching the horizontal axis.
-   Total area: The total area under the curve is equal to 1, representing the probability of all possible outcomes.

## Calculating Z-scores

A z-score is a standardized measure that indicates the relative position of a data point within a distribution. It is calculated using the following formula:

$z = \frac{(x - \mu)}{\sigma}$

where:

-   $z$ is the z-score
-   $x$ is the individual observation
-   $\mu$ is the mean of the distribution
-   $\sigma$ is the standard deviation of the distribution

```{=html}
<center>
<div width="90%">
<iframe src="https://byuimath.com/apps/normprob.html?width=600&z=1&height=400&left=1&mid=0&right=1&area=a&static=0&title=1&border=0" frameborder="0" width="650" height="450" data-external="1"></iframe>
</div>
</center>
```

68-95-99.7 Rule: Approximately 68% of the observations fall within one standard deviation of the mean ($\mu \pm \sigma$), 95% within two standard deviations ($\mu \pm 2\sigma$), and 99.7% within three standard deviations ($\mu \pm 3\sigma$).


```{=html}
<center>
<div width="90%">
<iframe src="https://byuimath.com/apps/normprobwitht.html?width=600&z=1&height=400&left=1&mid=0&right=1&area=a&static=0&title=1&border=0" frameborder="0" width="650" height="450" data-external="1"></iframe>
</div>
</center>
```