---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Univariate Hypothesis Testing

## Null Hypothesis Significance Testing

The central dogma of statistics is to make estimates about the population based on samples. Null Hypothesis Significance Testing (NHST) is a widely used statistical approach for testing the validity of a claim or hypothesis about a population based on sample data. The process involves comparing the observed data to what would be expected under a null hypothesis, which usually assumes no effect or relationship between variables.

**Null Hypothesis**

The null hypothesis (denoted as $H_0$) is a statement of no effect or no difference. It represents the default assumption that there is no relationship between the variables under investigation or that the treatment has no effect. The null hypothesis typically asserts that the observations are the result of chance or that the observed differences can be attributed to random variation.

**Alternative Hypothesis**

The alternative hypothesis (denoted as $H_a$) is a statement that contradicts the null hypothesis. It represents the claim that there is a relationship between the variables or that the treatment has an effect. The alternative hypothesis is what researchers hope to provide evidence for through the process of hypothesis testing.

### The Process of Null Hypothesis Significance Testing

1.  State the **null hypothesis** ($H_0$) and **alternative hypothesis** ($H_a$). The null hypothesis is a statement of no effect or relationship between the variables being tested, while the alternative hypothesis is a statement that claims some effect or relationship between the variables.

2.  Choose a **significance level**. The significance level, denoted by $\alpha$, is the probability of rejecting the null hypothesis when it is true. The most commonly used significance level is 0.05

3.  Collect data and calculate the **test statistic**. Gather your sample data and perform the appropriate statistical test to calculate the test statistic. The test statistic is a numerical value that measures the difference between the observed data and what would be expected under the null hypothesis. Different tests use different test statistics meaning each one is denoted differently dependent on which test. Common test statistics include $z$, $t$, $F$, or $\chi^2$.

4.  Determine the **p-value**. The p-value, denoted as $p$, is the probability of observing a test statistic as extreme or more extreme than the one calculated from the sample data, assuming the null hypothesis is true. It quantifies the evidence against the null hypothesis. Lower p-values indicate stronger evidence against the null hypothesis since they imply that the observed results are less likely to have occurred by chance alone under the null hypothesis. In other words, a smaller p-value suggests that the observed effect or relationship between the variables is more likely to be genuine and not just a random occurrence. Conversely, higher p-values indicate weaker evidence against the null hypothesis. This means that the observed results are more likely to have occurred by chance under the null hypothesis, and there is insufficient evidence to suggest that the effect or relationship is genuine.

5.  Compare the p-value to the significance level ($\alpha$). If the p-value is less than or equal to the chosen significance level ($p \leq α$), then reject the null hypothesis in favor of the alternative hypothesis. This implies that there is statistically significant evidence to support the claim made by the alternative hypothesis. If the p-value is greater than the significance level ($p > α$), then do not reject the null hypothesis, as there is not enough evidence to support the alternative hypothesis

6.  Interpret the results and draw conclusions. Based on the comparison between the p-value and the significance level, make a conclusion about the null hypothesis. If you rejected the null hypothesis, this suggests the alternative hypothesis is supported by the data. If you failed to reject the null hypothesis, this means there is insufficient evidence to support the alternative hypothesis. Keep in mind that failing to reject the null hypothesis does not prove it is true; it simply means that the data does not provide strong evidence against it.

It is crucial to note that failing to reject the null hypothesis does not prove it is true; rather, it indicates that there is not enough evidence to conclude that the alternative hypothesis is true. Additionally, the p-value is subject to various limitations and potential misinterpretations, so it is essential to consider effect sizes, confidence intervals, and other aspects of the data when making conclusions from hypothesis testing.

# Z-test

**Step One**

Let $\mu_1$ represent the mean height of the American male population, and $\mu_2$ represent the mean height of male NBA players. The null hypothesis ($H_0$) and alternative hypothesis ($H_a$) are as follows:

$$
\begin{align*}
H_0 &: \mu_1 = \mu_2 \\
H_a &: \mu_1 \neq \mu_2
\end{align*}
$$

In other words, the null or status quo hypothesis states that there is no difference in heights between the American male population and NBA players. The alternative hypothesis states that NBA players could be taller or shorter than the American male average.

**Step Two**

I will choose a significance level of 0.05. In other words, If we assumed our null hypothesis were true and the sample we obtain would have been so extreme that we would have only have had a 5 percent chance or less of getting it, we will reject the null hypothesis.

**Step Three**

Since we know the population variance for height, we will use a z-test. 

Our collected data is below. It is a set of univariate data about height of NBA players. The population standard deviation is 2.75 inches for adult men in the US.

```{r}
#| warning: false
#| message: false
#| code-fold: true

library(tidyverse)
library(plotly)

df <- read_csv('data/height_nba.csv') %>% rename(Height = `Height (Inches)`)

(df %>% ggplot(aes(x=Height)) + 
  theme_classic() +
  geom_histogram(fill='lightblue', color="black", size=.1, alpha=.9, binwidth = 1) ) %>% 
  ggplotly()

```

4.  Determine the **p-value**. The p-value, denoted as $p$, is the probability of observing a test statistic as extreme or more extreme than the one calculated from the sample data, assuming the null hypothesis is true. It quantifies the evidence against the null hypothesis. Lower p-values indicate stronger evidence against the null hypothesis since they imply that the observed results are less likely to have occurred by chance alone under the null hypothesis. In other words, a smaller p-value suggests that the observed effect or relationship between the variables is more likely to be genuine and not just a random occurrence. Conversely, higher p-values indicate weaker evidence against the null hypothesis. This means that the observed results are more likely to have occurred by chance under the null hypothesis, and there is insufficient evidence to suggest that the effect or relationship is genuine.

5.  Compare the p-value to the significance level ($\alpha$). If the p-value is less than or equal to the chosen significance level ($p \leq α$), then reject the null hypothesis in favor of the alternative hypothesis. This implies that there is statistically significant evidence to support the claim made by the alternative hypothesis. If the p-value is greater than the significance level ($p > α$), then do not reject the null hypothesis, as there is not enough evidence to support the alternative hypothesis

6.  Interpret the results and draw conclusions. Based on the comparison between the p-value and the significance level, make a conclusion about the null hypothesis. If you rejected the null hypothesis, this suggests the alternative hypothesis is supported by the data. If you failed to reject the null hypothesis, this means there is insufficient evidence to support the alternative hypothesis. Keep in mind that failing to reject the null hypothesis does not prove it is true; it simply means that the data does not provide strong evidence against it.



A z-test is a statistical test used to determine whether there is a significant difference between a sample mean and a population mean or between two population means, assuming that the population standard deviation is known. The z-test is based on the standard normal distribution (z-distribution), and it is used when the sample size is large (typically n ≥ 30) or when the population is normally distributed.

**The Data**




